### ISSUE TITLE
question for you...

### ISSUE THREAD

**Issue by rmasci** [aeden/traceroute#4]
In my company we have to do a lot of end to end testing to make sure that the packets can get from point A to point B -- and many times there is a firewall blocking. I wrote a tool to check the connectivity  in Go that will ping the endpoint on a given port, and respond back if the port is open, closed or if it times out. Usually if it times out I'll consider it to be blocked by a firewall. Then we have to traceroute to find out where the packet gets blocked. I am not sure if there is a way to tell from a packet what device that packet timed out on. It would be nice for my tool to return that the packet was blocked, and on what device that packet was blocked by.

Thanks!!

Richard M.

**Comment by aeden** [comment]
The only thing you could do is determine which hops failed all of their retries. If you have no packets further down that return values, then you can surmise that the block is there. I'm not aware of any specific details that would be reliable to determine that the packet was blocked.
